import { useEffect, useState } from "react";
import { Link, useNavigate } from "react-router";
import { toast } from "sonner";

import { Alert, AlertDescription } from "~/components/ui/alert";
import { Button } from "~/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "~/components/ui/card";
import { Separator } from "~/components/ui/separator";
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "~/components/ui/tooltip";

import FileUpload from "../components/file-upload";
import DocumentDropdown from "../components/document-dropdown";
import AdditionalInfoForm from "../components/add-info-form";
import { ConfirmDialog } from "../components/confirm-dialog";
import { FileUploadDialog } from "../components/file-upload-dialog";
import { StatusBadge } from "../components/status-badge";
import {
  UPLOADABLE_DOCUMENT_TYPES,
  DOCUMENT_TYPE_LABELS,
  isSuratPengantarDocument,
} from "../constants/document-types";

import type {
  AdditionalInfoData,
  Member,
  Submission,
  SubmissionDocument,
} from "../types";
import { getMyTeams } from "~/feature/create-teams/services/team-api";
import { apiClient } from "~/lib/api-client";
import {
  getSubmissionByTeamId,
  uploadSubmissionDocument,
  updateSubmission,
  submitSubmission,
  deleteSubmissionDocument,
} from "~/lib/services/submission-api";
import { getSubmissionLetterRequestStatuses } from "~/lib/services/letter-request-status-api";
import {
  reapplySuratKesediaanApproval,
  requestSuratKesediaanApproval,
} from "~/lib/services/surat-kesediaan-api";
import {
  reapplySuratPermohonanApproval,
  requestSuratPermohonanApproval,
} from "~/lib/services/surat-permohonan-api";
import { getMyMahasiswaProfile } from "~/lib/services/mahasiswa-api";
import { useUser } from "~/contexts/user-context";
import { ArrowLeft, ArrowRight, Eye, Info } from "lucide-react";

function normalizePlaceholderValue(value?: string | null): string {
  if (!value) return "";
  return value.trim().toLowerCase() === "belum diisi" ? "" : value;
}

function getRequestKey(memberUserId: string, documentType: string): string {
  return `${memberUserId}:${documentType}`;
}

type LetterRequestStatusLabel = "MENUNGGU" | "DISETUJUI" | "DITOLAK";
type AutoSaveStatus = "idle" | "saving" | "saved" | "error";

function SubmissionPage() {
  const navigate = useNavigate();
  const { user, isLoading: isUserLoading, isAuthenticated } = useUser();

  const [isConfirmDialogOpen, setIsConfirmDialogOpen] = useState(false);
  const [isLoading, setIsLoading] = useState(true);
  const [loadError, setLoadError] = useState<string | null>(null);
  const [teamName, setTeamName] = useState<string>("");
  const [teamStatus, setTeamStatus] = useState<string>("");
  const [teamId, setTeamId] = useState<string>("");
  const [isCurrentUserLeader, setIsCurrentUserLeader] =
    useState<boolean>(false);

  const [submission, setSubmission] = useState<Submission | null>(null);
  const [submissionDocuments, setSubmissionDocuments] = useState<
    SubmissionDocument[]
  >([]);

  const [additionalInfo, setAdditionalInfo] = useState<AdditionalInfoData>({
    tujuanSurat: "",
    namaTempat: "",
    alamatTempat: "",
    teleponPerusahaan: "",
    jenisProdukUsaha: "",
    tanggalMulai: "",
    tanggalSelesai: "",
    divisi: "",
  });

  const [proposalFile, setProposalFile] = useState<File | null>(null);
  const [teamMembers, setTeamMembers] = useState<Member[]>([]);
  const [submittedRequestKeys, setSubmittedRequestKeys] = useState<Set<string>>(
    new Set(),
  );
  const [submittedRequestStatusByKey, setSubmittedRequestStatusByKey] =
    useState<Record<string, LetterRequestStatusLabel>>({});
  const [signedUrlByKey, setSignedUrlByKey] = useState<Record<string, string>>(
    {},
  );
  const [latestRequestIdByKey, setLatestRequestIdByKey] = useState<
    Record<string, string>
  >({});
  const [rejectionReasonByKey, setRejectionReasonByKey] = useState<
    Record<string, string>
  >({});
  const [dosenNameByKey, setDosenNameByKey] = useState<Record<string, string>>(
    {},
  );
  const [autoSaveStatus, setAutoSaveStatus] = useState<AutoSaveStatus>("idle");
  const [autoSaveError, setAutoSaveError] = useState<string | null>(null);
  const [isProposalReuploadConfirmOpen, setIsProposalReuploadConfirmOpen] =
    useState(false);
  const [isProposalUploadDialogOpen, setIsProposalUploadDialogOpen] =
    useState(false);

  const proposalDocument = submissionDocuments.find(
    (doc) => doc.documentType === "PROPOSAL_KETUA",
  );

  // ✅ Use constants to ensure SURAT_PENGANTAR is excluded
  // SURAT_PENGANTAR is auto-generated by system after approval
  const documents = UPLOADABLE_DOCUMENT_TYPES.filter(
    (type) => type !== "PROPOSAL_KETUA",
  ) // Proposal handled separately
    .map((type, index) => ({
      id: index + 1,
      title: DOCUMENT_TYPE_LABELS[type],
      type: type,
    }));

  // ✅ Filter submission documents - EXCLUDE SURAT_PENGANTAR from upload form
  // SURAT_PENGANTAR hanya dibuat otomatis oleh backend saat approve
  const filteredSubmissionDocuments = submissionDocuments.filter(
    (doc) => !isSuratPengantarDocument(doc.documentType),
  );

  const loadSubmittedRequestStatuses = async (submissionId: string) => {
    try {
      const response = await getSubmissionLetterRequestStatuses(submissionId);

      if (!response.success || !response.data) {
        console.warn(
          "⚠️ Failed to load letter request statuses:",
          response.message,
        );
        return;
      }

      if (response.data.length === 0) {
        console.warn(
          "⚠️ Letter request status endpoint returned no parsable items for submission:",
          submissionId,
        );
      }

      const nextKeys = new Set<string>();
      const nextStatuses: Record<string, LetterRequestStatusLabel> = {};

      response.data.forEach((item) => {
        if (item.isAlreadySubmitted) {
          const requestKey = getRequestKey(
            item.memberUserId,
            item.documentType,
          );
          nextKeys.add(requestKey);
          nextStatuses[requestKey] = item.latestStatus ?? "MENUNGGU";
        }
      });

      setSubmittedRequestKeys(nextKeys);
      setSubmittedRequestStatusByKey(nextStatuses);
      const nextSignedUrls: Record<string, string> = {};
      const nextLatestRequestIds: Record<string, string> = {};
      const nextRejectionReasons: Record<string, string> = {};
      const nextDosenNames: Record<string, string> = {};
      response.data.forEach((item) => {
        const requestKey = getRequestKey(item.memberUserId, item.documentType);
        if (item.signedFileUrl) nextSignedUrls[requestKey] = item.signedFileUrl;
        if (item.latestRequestId)
          nextLatestRequestIds[requestKey] = item.latestRequestId;
        if (item.rejectionReason)
          nextRejectionReasons[requestKey] = item.rejectionReason;
        if (item.dosenName) nextDosenNames[requestKey] = item.dosenName;
      });
      setSignedUrlByKey(nextSignedUrls);
      setLatestRequestIdByKey(nextLatestRequestIds);
      setRejectionReasonByKey(nextRejectionReasons);
      setDosenNameByKey(nextDosenNames);
    } catch (error) {
      console.error("❌ Error loading letter request statuses:", error);
    }
  };

  // Status REJECTED dianggap sudah pernah diajukan, sehingga input dikunci
  // sampai user klik "Ajukan Ulang" di halaman surat pengantar.
  const isSubmissionSubmitted =
    submission?.status === "PENDING_REVIEW" ||
    submission?.status === "APPROVED" ||
    submission?.status === "REJECTED";

  // Fetch team data (finalized) for current user
  useEffect(() => {
    if (isUserLoading) return;
    if (!isAuthenticated) {
      navigate("/login");
      return;
    }

    const loadTeam = async () => {
      try {
        setIsLoading(true);
        setLoadError(null);
        const response = await getMyTeams();

        if (response.success && Array.isArray(response.data)) {
          const fixedTeam =
            response.data.find((t) => t.status?.toUpperCase() === "FIXED") ||
            response.data[0];

          if (!fixedTeam) {
            setLoadError(
              "Tim tidak ditemukan. Silakan buat tim terlebih dahulu.",
            );
            setTeamMembers([]);
            return;
          }

          const acceptedMembers = (fixedTeam.members || []).filter(
            (m) => m.status === "ACCEPTED",
          );

          const mappedMembers: Member[] = acceptedMembers.map((m) => ({
            id: m.user.id,
            name: m.user.name,
            nim: m.user.nim,
            role: m.role === "KETUA" ? "Ketua" : "Anggota",
          }));

          // Sort: Ketua urutan atas, baru anggota
          mappedMembers.sort((a, b) => {
            if (a.role === "Ketua" && b.role !== "Ketua") return -1;
            if (a.role !== "Ketua" && b.role === "Ketua") return 1;
            return 0;
          });

          setTeamMembers(mappedMembers);
          setTeamName(fixedTeam.name || fixedTeam.code || "Tim KP");
          setTeamStatus(fixedTeam.status || "");
          setTeamId(fixedTeam.id);

          // Tentukan apakah user adalah ketua
          const currentUserMember = mappedMembers.find(
            (m) => m.id === user?.id,
          );
          setIsCurrentUserLeader(currentUserMember?.role === "Ketua");

          // Fetch submission dari database
          const submissionResponse = await getSubmissionByTeamId(fixedTeam.id);
          if (submissionResponse.success && submissionResponse.data) {
            const submissionData = submissionResponse.data as Submission & {
              company_phone?: string;
              company_business_type?: string;
            };

            setSubmission(submissionResponse.data);
            if (submissionResponse.data.documents) {
              setSubmissionDocuments(submissionResponse.data.documents);
            }
            await loadSubmittedRequestStatuses(submissionResponse.data.id);
            // form dengan data submission pada db yang ada
            setAdditionalInfo({
              tujuanSurat: normalizePlaceholderValue(
                submissionData.letterPurpose,
              ),
              namaTempat: normalizePlaceholderValue(submissionData.companyName),
              alamatTempat: normalizePlaceholderValue(
                submissionData.companyAddress,
              ),
              teleponPerusahaan:
                normalizePlaceholderValue(submissionData.companyPhone) ||
                normalizePlaceholderValue(submissionData.company_phone),
              jenisProdukUsaha:
                normalizePlaceholderValue(submissionData.companyBusinessType) ||
                normalizePlaceholderValue(submissionData.company_business_type),
              tanggalMulai: submissionData.startDate || "",
              tanggalSelesai: submissionData.endDate || "",
              divisi: normalizePlaceholderValue(submissionData.division),
            });
          } else {
            // Jika belum ada submission, siapkan form kosong
            setSubmission(null);
            setSubmissionDocuments([]);
            setSubmittedRequestKeys(new Set());
            setSubmittedRequestStatusByKey({});
            setSignedUrlByKey({});
            setLatestRequestIdByKey({});
            setRejectionReasonByKey({});
            setDosenNameByKey({});
          }
        } else {
          setLoadError(response.message || "Gagal memuat data tim");
        }
      } catch (error) {
        console.error("❌ Error loading team members:", error);
        setLoadError(
          error instanceof Error ? error.message : "Gagal memuat data tim",
        );
      } finally {
        setIsLoading(false);
      }
    };

    void loadTeam();
  }, [isUserLoading, isAuthenticated, navigate]);

  const handleProposalUpload = async (file: File) => {
    if (!user) return;

    try {
      setIsLoading(true);

      const currentSubmission = submission;
      if (!currentSubmission) {
        toast.error(
          "Draft submission belum tersedia. Silakan tetapkan tim terlebih dahulu dari halaman Buat Tim.",
        );
        return;
      }

      const response = await uploadSubmissionDocument(
        currentSubmission.id,
        "PROPOSAL_KETUA",
        user.id,
        file,
        user.id,
      );

      if (response.success && response.data) {
        const docToAdd = response.data;

        // ✅ NEW: Delete old REJECTED proposal from backend if exists
        const oldRejectedProposal = submissionDocuments.find(
          (doc) =>
            doc.documentType === "PROPOSAL_KETUA" && doc.status === "REJECTED",
        );

        if (oldRejectedProposal) {
          console.log(
            `🗑️ Deleting old REJECTED proposal (${oldRejectedProposal.id})...`,
          );
          await deleteSubmissionDocument(oldRejectedProposal.id);
        }

        setSubmissionDocuments((prev) => {
          // Hapus proposal lama jika ada
          const filtered = prev.filter(
            (doc) => doc.documentType !== "PROPOSAL_KETUA",
          );
          return [...filtered, docToAdd];
        });
        setProposalFile(file);
        toast.success("Proposal berhasil diupload dengan status PENDING");
      } else {
        toast.error(response.message || "Gagal mengupload proposal");
      }
    } catch (error) {
      console.error("❌ Error uploading proposal:", error);
      toast.error("Terjadi kesalahan saat mengupload proposal");
    } finally {
      setIsLoading(false);
    }
  };

  /**
   * Fetch & refresh semua documents untuk submission dari backend
   * Ini dipanggil setelah upload untuk sync dengan dokumen dari anggota lain
   */
  const refreshSubmissionDocuments = async (submissionId: string) => {
    try {
      const docsResponse = await apiClient<SubmissionDocument[]>(
        `/api/submissions/${submissionId}/documents`,
      );

      if (docsResponse.success && docsResponse.data) {
        console.log(
          `📄 Fetched ${docsResponse.data.length} documents from server`,
          docsResponse.data,
        );
        setSubmissionDocuments(docsResponse.data);
      } else {
        console.warn("⚠️ Failed to refresh documents:", docsResponse.message);
      }
    } catch (error) {
      console.error("❌ Error refreshing documents:", error);
    }
  };

  const handleDocumentUpload = async (
    docId: number,
    memberId: string,
    file: File,
  ) => {
    try {
      setIsLoading(true);

      const currentSubmission = submission;
      if (!currentSubmission) {
        toast.error(
          "Draft submission belum tersedia. Silakan tetapkan tim terlebih dahulu dari halaman Buat Tim.",
        );
        return;
      }

      const docInfo = documents.find((d) => d.id === docId);
      if (!docInfo) {
        toast.error("Tipe dokumen tidak dikenali");
        return;
      }

      // ✅ NEW: Check if document already exists with REJECTED status
      // If exists, delete it before uploading new one
      const existingDoc = submissionDocuments.find(
        (doc) =>
          doc.documentType === docInfo.type && doc.memberUserId === memberId,
      );

      if (existingDoc && existingDoc.status === "REJECTED") {
        console.log(
          `🗑️ Deleting old REJECTED document (${existingDoc.id}) before reupload...`,
        );
        const deleteResponse = await deleteSubmissionDocument(existingDoc.id);

        if (!deleteResponse.success) {
          console.warn(
            "⚠️ Failed to delete old document, but continuing with upload...",
          );
          // Continue anyway - backend might handle this automatically
        } else {
          console.log("✅ Old REJECTED document deleted successfully");
          toast.success("Dokumen lama yang ditolak berhasil dihapus");
        }
      }

      const response = await uploadSubmissionDocument(
        currentSubmission.id,
        docInfo.type,
        memberId,
        file,
        user?.id,
      );

      if (response.success && response.data) {
        toast.success(
          `${docInfo.title} berhasil diupload dengan status PENDING`,
        );

        // ✅ KEY FIX: Re-fetch semua documents dari server
        // Ini memastikan dokumen dari user lain juga terlihat
        console.log("🔄 Re-fetching all documents from server...");
        await refreshSubmissionDocuments(currentSubmission.id);
      } else {
        toast.error(response.message || "Gagal mengupload dokumen");
      }
    } catch (error) {
      console.error("❌ Error uploading document:", error);
      toast.error("Terjadi kesalahan saat mengupload dokumen");
    } finally {
      setIsLoading(false);
    }
  };

  const handleAjukanSurat = async (
    memberId: string,
    documentType: string,
  ): Promise<boolean> => {
    const requestKey = getRequestKey(memberId, documentType);
    const currentStatus = submittedRequestStatusByKey[requestKey];
    const latestRequestId = latestRequestIdByKey[requestKey];

    if (submittedRequestKeys.has(requestKey) && currentStatus !== "DITOLAK") {
      return true;
    }

    if (documentType === "FORM_PERMOHONAN") {
      try {
        const profileResponse = await getMyMahasiswaProfile();
        const mahasiswaEsignatureUrl =
          profileResponse.success && profileResponse.data?.esignature?.url
            ? profileResponse.data.esignature.url
            : undefined;

        const response =
          currentStatus === "DITOLAK" && latestRequestId
            ? await reapplySuratPermohonanApproval(
                latestRequestId,
                memberId,
                mahasiswaEsignatureUrl,
              )
            : await requestSuratPermohonanApproval(
                memberId,
                mahasiswaEsignatureUrl,
              );
        if (response.success) {
          toast.success(
            currentStatus === "DITOLAK"
              ? "Pengajuan ulang surat permohonan berhasil dikirim ke dosen."
              : "Pengajuan surat permohonan berhasil dikirim ke dosen.",
          );

          if (response.data?.requestId) {
            setLatestRequestIdByKey((prev) => ({
              ...prev,
              [requestKey]: response.data?.requestId as string,
            }));
          }

          setSubmittedRequestKeys((prev) => {
            const next = new Set(prev);
            next.add(requestKey);
            return next;
          });
          setSubmittedRequestStatusByKey((prev) => ({
            ...prev,
            [requestKey]: "MENUNGGU",
          }));
          setRejectionReasonByKey((prev) => {
            const next = { ...prev };
            delete next[requestKey];
            return next;
          });
          setSignedUrlByKey((prev) => {
            const next = { ...prev };
            delete next[requestKey];
            return next;
          });
          return true;
        } else {
          toast.error(response.message || "Gagal mengajukan surat permohonan.");
          return false;
        }
      } catch (error) {
        console.error("❌ Error requesting surat permohonan:", error);
        toast.error("Terjadi kesalahan saat mengajukan surat permohonan.");
        return false;
      }
    } else {
      try {
        const response =
          currentStatus === "DITOLAK" && latestRequestId
            ? await reapplySuratKesediaanApproval(latestRequestId, memberId)
            : await requestSuratKesediaanApproval(memberId);

        if (!response.success) {
          toast.error(response.message || "Gagal mengajukan surat kesediaan.");
          return false;
        }

        toast.success(
          currentStatus === "DITOLAK"
            ? "Pengajuan ulang surat kesediaan berhasil dikirim ke dosen."
            : "Pengajuan surat kesediaan berhasil dikirim ke dosen.",
        );

        if (response.data?.requestId) {
          setLatestRequestIdByKey((prev) => ({
            ...prev,
            [requestKey]: response.data?.requestId as string,
          }));
        }

        setSubmittedRequestKeys((prev) => {
          const next = new Set(prev);
          next.add(requestKey);
          return next;
        });
        setSubmittedRequestStatusByKey((prev) => ({
          ...prev,
          [requestKey]: "MENUNGGU",
        }));
        setRejectionReasonByKey((prev) => {
          const next = { ...prev };
          delete next[requestKey];
          return next;
        });
        setSignedUrlByKey((prev) => {
          const next = { ...prev };
          delete next[requestKey];
          return next;
        });
        return true;
      } catch (error) {
        console.error("❌ Error requesting surat kesediaan:", error);
        toast.error("Terjadi kesalahan saat mengajukan surat kesediaan.");
        return false;
      }
    }
  };

  const handleAdditionalInfoChange = async (data: AdditionalInfoData) => {
    setAdditionalInfo(data);

    // Auto-save ke database dengan user feedback
    if (submission) {
      try {
        setAutoSaveStatus("saving");
        setAutoSaveError(null);

        const response = await updateSubmission(submission.id, {
          letterPurpose: data.tujuanSurat,
          companyName: data.namaTempat,
          companyAddress: data.alamatTempat,
          companyPhone: data.teleponPerusahaan,
          companyBusinessType: data.jenisProdukUsaha,
          division: data.divisi,
          startDate: data.tanggalMulai,
          endDate: data.tanggalSelesai,
        });

        if (response.success) {
          console.log("✅ Auto-saved successfully");
          setAutoSaveStatus("saved");
          window.setTimeout(() => {
            setAutoSaveStatus("idle");
          }, 1500);
        } else {
          throw new Error(response.message || "Gagal menyimpan perubahan");
        }
      } catch (error) {
        console.error("❌ Error auto-saving submission:", error);
        setAutoSaveStatus("error");
        setAutoSaveError(
          error instanceof Error ? error.message : "Gagal menyimpan",
        );
      }
    }
  };

  const handleSubmit = async () => {
    if (isLoading) return;
    if (!teamMembers.length) {
      toast.error(
        "Tim belum tersedia atau belum final. Lengkapi tim terlebih dahulu.",
      );
      return;
    }

    try {
      setIsLoading(true);

      if (!submission) {
        toast.error(
          "Draft submission belum tersedia. Silakan kembali ke halaman Buat Tim dan tetapkan tim terlebih dahulu.",
        );
        return;
      }

      // Submit submission (ubah status ke PENDING_REVIEW)
      const submissionId = submission?.id || "";
      console.log("📤 Submitting submission:", { submissionId, teamId });

      if (!submissionId) {
        toast.error("Submission ID tidak valid. Silakan coba ulang.");
        return;
      }

      const submitResponse = await submitSubmission(submissionId);
      console.log("📥 Submit response:", submitResponse);

      if (submitResponse.success) {
        toast.success("Surat pengantar berhasil diajukan!");
        console.log("✅ Submission berhasil di-submit:", submitResponse.data);
        navigate("/mahasiswa/kp/surat-pengantar");
      } else {
        const errorMsg =
          submitResponse.message || "Gagal mengajukan surat pengantar";
        console.error("❌ Submit failed:", errorMsg);
        toast.error(errorMsg);
      }

      setIsConfirmDialogOpen(false);
    } catch (error) {
      console.error("❌ Error submitting:", error);
      const errorMessage =
        error instanceof Error
          ? error.message
          : "Terjadi kesalahan saat mengajukan surat pengantar";
      toast.error(errorMessage);
    } finally {
      setIsLoading(false);
    }
  };

  const handlePreviewProposal = () => {
    if (proposalDocument?.fileUrl) {
      window.open(proposalDocument.fileUrl, "_blank", "noopener,noreferrer");
      return;
    }

    if (proposalFile) {
      try {
        const fileURL = URL.createObjectURL(proposalFile);
        window.open(fileURL, "_blank", "noopener,noreferrer");
        setTimeout(() => URL.revokeObjectURL(fileURL), 100);
        return;
      } catch {
        toast.error("Tidak dapat menampilkan pratinjau file.");
        return;
      }
    }

    toast.error("File proposal belum tersedia untuk dipreview.");
  };

  const handleConfirmProposalReupload = () => {
    setIsProposalReuploadConfirmOpen(false);
    setIsProposalUploadDialogOpen(true);
  };

  // Validasi kelengkapan dokumen dan form
  const validateSubmission = () => {
    const missingItems: string[] = [];

    // 1. Cek proposal ketua
    if (!proposalDocument) {
      missingItems.push("Surat Proposal (Ketua Tim)");
    }

    // 2. Cek dokumen pribadi setiap anggota
    teamMembers.forEach((member) => {
      documents.forEach((doc) => {
        const uploaded = filteredSubmissionDocuments.some(
          (submittedDoc) =>
            submittedDoc.documentType === doc.type &&
            submittedDoc.memberUserId === member.id,
        );
        if (!uploaded) {
          missingItems.push(`${doc.title} - ${member.name}`);
        }
      });
    });

    // 3. Cek keterangan lain
    if (!additionalInfo.tujuanSurat?.trim()) {
      missingItems.push("Tujuan Surat");
    }
    if (!additionalInfo.namaTempat?.trim()) {
      missingItems.push("Nama Tempat KP");
    }
    if (!additionalInfo.alamatTempat?.trim()) {
      missingItems.push("Alamat Tempat KP");
    }
    if (!additionalInfo.divisi?.trim()) {
      missingItems.push("Nama Unit/Divisi");
    }
    if (!additionalInfo.teleponPerusahaan?.trim()) {
      missingItems.push("Telepon Perusahaan");
    }
    if (!additionalInfo.jenisProdukUsaha?.trim()) {
      missingItems.push("Jenis Produk/Usaha");
    }
    if (!additionalInfo.tanggalMulai) {
      missingItems.push("Tanggal Mulai KP");
    }
    if (!additionalInfo.tanggalSelesai) {
      missingItems.push("Tanggal Selesai KP");
    }

    return {
      isValid: missingItems.length === 0,
      missingItems,
    };
  };

  if (isUserLoading || isLoading) {
    return (
      <div className="flex items-center justify-center min-h-[400px]">
        <p className="text-muted-foreground">Memuat data tim...</p>
      </div>
    );
  }

  if (loadError) {
    return (
      <div className="space-y-4">
        <Alert variant="destructive">
          <AlertDescription>{loadError}</AlertDescription>
        </Alert>
        <Button onClick={() => navigate("/mahasiswa/kp/buat-tim")}>
          Kembali ke Buat Tim
        </Button>
      </div>
    );
  }

  return (
    <>
      {/* Header Section */}
      <div className="mb-8">
        <h1 className="text-3xl font-bold text-foreground mb-2">
          Halaman Pengajuan Syarat Kerja Praktik
        </h1>
        <p className="text-muted-foreground">
          Upload dokumen-dokumen yang diperlukan untuk melaksanakan Kerja
          Praktik
        </p>
        {teamName && (
          <p className="text-sm text-muted-foreground mt-2">
            Tim: {teamName} ({teamMembers.length} anggota, status{" "}
            {teamStatus || "-"})
          </p>
        )}
      </div>

      {/* Info Alert */}
      {submission?.status === "DRAFT" && (
        <Alert className="mb-8 border-l-4 border-primary bg-primary/5">
          <Info className="h-5 w-5 text-primary" />
          <AlertDescription className="text-foreground">
            Pastikan semua dokumen telah diupload sebelum melakukan pengajuan
          </AlertDescription>
        </Alert>
      )}

      {/* Approval Locked Alert */}
      {submission?.status === "APPROVED" && (
        <Alert className="mb-8 border-l-4 border-green-600 bg-green-600/5">
          <Info className="h-5 w-5 text-green-600" />
          <AlertDescription className="text-green-700 dark:text-green-400">
            Pengajuan telah disetujui. Data tidak dapat diubah lagi.
          </AlertDescription>
        </Alert>
      )}

      {/* ✅ NEW: Rejection Alert */}
      {submission?.status === "REJECTED" && (
        <Alert className="mb-8 border-l-4 border-destructive bg-destructive/5">
          <AlertDescription className="text-destructive">
            <div className="font-semibold mb-2">
              Pengajuan Ditolak - Silakan Lakukan Perbaikan
            </div>
            <p className="text-sm mb-3">
              Beberapa dokumen yang Anda ajukan perlu diperbaiki. Sebelum
              melakukan perbaikan di halaman ini, Anda wajib menekan tombol{" "}
              <strong>Ajukan Ulang</strong> terlebih dahulu pada halaman{" "}
              <strong>Surat Pengantar</strong>. Setelah itu, dokumen berstatus{" "}
              <strong>Ditolak</strong> dapat diupload ulang.
            </p>
            {submission.rejectionReason && (
              <div className="mt-3 p-2 bg-white dark:bg-slate-900 rounded border border-destructive/30">
                <p className="text-xs font-semibold mb-1">💬 Catatan Admin:</p>
                <p className="text-sm">{submission.rejectionReason}</p>
              </div>
            )}
          </AlertDescription>
        </Alert>
      )}

      {/* Pending Review Locked Alert */}
      {submission?.status === "PENDING_REVIEW" && (
        <Alert className="mb-8 border-l-4 border-amber-600 bg-amber-600/5">
          <Info className="h-5 w-5 text-amber-600" />
          <AlertDescription className="text-amber-700 dark:text-amber-400">
            Pengajuan sedang dalam review. Data tidak dapat diubah hingga proses
            review selesai.
          </AlertDescription>
        </Alert>
      )}

      <Card className="mb-8">
        <CardContent className="p-6">
          {/* Keterangan Lain Section */}
          <div className="mb-8">
            <AdditionalInfoForm
              initialData={additionalInfo}
              onDataChange={handleAdditionalInfoChange}
              isEditable={isCurrentUserLeader && !isSubmissionSubmitted}
              autoSaveStatus={autoSaveStatus}
              autoSaveError={autoSaveError}
            />
          </div>

          {/* Surat Proposal Section */}
          <div className="mb-8">
            <CardHeader className="px-0 pt-0">
              <CardTitle className="text-xl font-semibold text-foreground">
                Surat Proposal
              </CardTitle>
            </CardHeader>
            <Separator className="mb-4" />
            <div className="flex flex-wrap items-start gap-3">
              <div
                className={
                  isCurrentUserLeader && !proposalDocument ? "flex-grow" : ""
                }
              >
                {isCurrentUserLeader ? (
                  proposalDocument ? (
                    <div className="mb-2">
                      <p className="block font-medium mb-2">
                        Upload Surat Proposal (Ketua Tim)
                      </p>
                      <div className="flex items-center gap-2 flex-wrap">
                        <Button
                          size="sm"
                          className="w-full sm:w-auto"
                          onClick={() => setIsProposalReuploadConfirmOpen(true)}
                          disabled={isSubmissionSubmitted}
                        >
                          Terupload
                        </Button>
                        {(proposalDocument || proposalFile) && (
                          <TooltipProvider>
                            <Tooltip>
                              <TooltipTrigger asChild>
                                <Button
                                  variant="ghost"
                                  size="icon"
                                  onClick={handlePreviewProposal}
                                  className="text-muted-foreground hover:text-foreground"
                                >
                                  <Eye className="size-5" />
                                </Button>
                              </TooltipTrigger>
                              <TooltipContent>
                                <p>Preview File</p>
                              </TooltipContent>
                            </Tooltip>
                          </TooltipProvider>
                        )}
                      </div>
                      <p className="text-xs text-muted-foreground mt-2">
                        {submission?.status === "REJECTED"
                          ? "Proposal dikunci sementara. Klik Ajukan Ulang di halaman Surat Pengantar terlebih dahulu."
                          : "Klik untuk upload ulang proposal ketua tim."}
                      </p>
                      {proposalDocument?.status &&
                        proposalDocument.status !== "PENDING" && (
                          <div className="mt-2">
                            <StatusBadge
                              status={proposalDocument.status}
                              size="sm"
                            />
                          </div>
                        )}
                    </div>
                  ) : (
                    <FileUpload
                      label="Upload Surat Proposal (Ketua Tim)"
                      onFileChange={handleProposalUpload}
                      disabled={isSubmissionSubmitted}
                    />
                  )
                ) : (
                  <div className="mb-2">
                    <p className="block font-medium mb-2">
                      Upload Surat Proposal (Ketua Tim)
                    </p>
                    <div className="flex items-center gap-2 flex-wrap">
                      <Button
                        size="sm"
                        className={
                          proposalDocument
                            ? "w-full sm:w-auto opacity-50 cursor-not-allowed"
                            : "w-full sm:w-auto opacity-50 cursor-not-allowed"
                        }
                        variant={proposalDocument ? "default" : "destructive"}
                        disabled
                      >
                        {proposalDocument ? "Terupload" : "Belum diupload"}
                      </Button>
                      {proposalDocument && (
                        <TooltipProvider>
                          <Tooltip>
                            <TooltipTrigger asChild>
                              <Button
                                variant="ghost"
                                size="icon"
                                onClick={handlePreviewProposal}
                                className="text-muted-foreground hover:text-foreground"
                              >
                                <Eye className="size-5" />
                              </Button>
                            </TooltipTrigger>
                            <TooltipContent>
                              <p>Preview File</p>
                            </TooltipContent>
                          </Tooltip>
                        </TooltipProvider>
                      )}
                    </div>
                    <p className="text-xs text-muted-foreground mt-2">
                      Proposal hanya bisa diupload oleh ketua tim.
                    </p>
                    {proposalDocument?.status &&
                      proposalDocument.status !== "PENDING" && (
                        <div className="mt-2">
                          <StatusBadge
                            status={proposalDocument.status}
                            size="sm"
                          />
                        </div>
                      )}
                  </div>
                )}
              </div>
            </div>
          </div>

          {/* Lampiran Berkas Pribadi Section */}
          <div className="mb-8">
            <CardHeader className="px-0 pt-0">
              <CardTitle className="text-xl font-semibold text-foreground">
                Lampiran Berkas Pribadi
              </CardTitle>
            </CardHeader>
            <Separator className="mb-4" />
            {documents.map((document) => (
              <DocumentDropdown
                key={document.id}
                document={document}
                members={teamMembers}
                documents={filteredSubmissionDocuments}
                currentUserId={user?.id}
                submittedRequestKeys={submittedRequestKeys}
                submittedRequestStatusByKey={submittedRequestStatusByKey}
                dosenNameByKey={dosenNameByKey}
                onUpload={handleDocumentUpload}
                onSubmitRequest={handleAjukanSurat}
                disabled={isSubmissionSubmitted}
                signedUrlByKey={signedUrlByKey}
                rejectionReasonByKey={rejectionReasonByKey}
              />
            ))}
          </div>

          {/* Submit Button */}
          <div className="text-center mt-8">
            <Button
              onClick={() => {
                const validation = validateSubmission();
                if (!validation.isValid) {
                  toast.error(`Harap lengkapi semua data yang diperlukan!`, {
                    duration: 6000,
                  });
                  return;
                }
                setIsConfirmDialogOpen(true);
              }}
              size="lg"
              className="px-8 py-3 font-medium text-lg"
              disabled={!isCurrentUserLeader || isSubmissionSubmitted}
            >
              {submission?.status === "PENDING_REVIEW"
                ? "Telah Diajukan"
                : submission?.status === "APPROVED"
                  ? "Telah Disetujui"
                  : submission?.status === "REJECTED"
                    ? "Telah Diajukan"
                    : "Ajukan Surat Pengantar"}
            </Button>
          </div>
        </CardContent>
      </Card>

      {/* Navigation Buttons - Always show */}
      <div className="flex justify-between mt-8">
        <Button variant="secondary" asChild className="px-6 py-3 font-medium">
          <Link to="/mahasiswa/kp/buat-tim">
            <ArrowLeft className="mr-2 h-4 w-4" />
            Sebelumnya
          </Link>
        </Button>
        <Button
          className="px-6 py-3 font-medium"
          disabled={
            submission?.status !== "PENDING_REVIEW" &&
            submission?.status !== "APPROVED" &&
            submission?.status !== "REJECTED"
          }
          onClick={() => {
            if (
              submission?.status === "PENDING_REVIEW" ||
              submission?.status === "APPROVED" ||
              submission?.status === "REJECTED"
            ) {
              navigate("/mahasiswa/kp/surat-pengantar");
            }
          }}
        >
          Selanjutnya
          <ArrowRight className="ml-2 h-4 w-4" />
        </Button>
      </div>
      <ConfirmDialog
        open={isProposalReuploadConfirmOpen}
        onOpenChange={setIsProposalReuploadConfirmOpen}
        title="Upload Ulang Proposal?"
        description="File proposal yang lama akan diganti. Lanjutkan upload ulang?"
        onConfirm={handleConfirmProposalReupload}
        confirmText="Ya, Upload Ulang"
        cancelText="Batal"
      />

      <FileUploadDialog
        open={isProposalUploadDialogOpen}
        onOpenChange={setIsProposalUploadDialogOpen}
        onFileUpload={(file) => void handleProposalUpload(file)}
        memberName="Ketua Tim"
        documentTitle="Surat Proposal"
      />

      <ConfirmDialog
        open={isConfirmDialogOpen}
        onOpenChange={setIsConfirmDialogOpen}
        title="Konfirmasi Pengajuan"
        description={
          <>
            Apakah Anda yakin ingin mengajukan surat pengantar? Pastikan semua
            data dan dokumen yang Anda masukkan sudah benar.
            <br />
            <br />
            <span className="block">
              <span className="font-semibold text-red-700">Peringatan:</span>{" "}
              <span className="font-semibold inline-block">
                Anda tidak akan dapat mengubah data pengajuan hingga proses
                review selesai.
              </span>
            </span>
          </>
        }
        onConfirm={handleSubmit}
        confirmText="Ya, Ajukan"
        cancelText="Batal"
        variant="default"
      />
    </>
  );
}

export default SubmissionPage;
