import type {
  Submission,
  SubmissionDocument,
} from "~/feature/submission/types";
import type {
  Application,
  DocumentFile,
  Member,
  WakilDekanSignature,
} from "~/feature/submission/types";
import {
  DOCUMENT_TYPE_LABELS,
  isSuratPengantarDocument,
} from "../constants/document-types";

/**
 * Mapping document type dari backend ke display title
 * ⚠️ SURAT_PENGANTAR excluded - it's auto-generated by system, not uploadable
 * Menggunakan constants dari document-types.ts
 */
const DOCUMENT_TYPE_MAPPING = DOCUMENT_TYPE_LABELS;

/**
 * Mapping submission document dari backend ke DocumentFile untuk review modal
 */
function mapSubmissionDocumentToDocumentFile(
  doc: SubmissionDocument,
  memberName: string,
): DocumentFile {
  const title = DOCUMENT_TYPE_MAPPING[doc.documentType] || doc.documentType;

  return {
    id: doc.id,
    title,
    uploadedBy: memberName,
    uploadDate: new Date(doc.createdAt).toLocaleDateString("id-ID", {
      day: "2-digit",
      month: "2-digit",
      year: "numeric",
    }),
    status: "uploaded",
    url: doc.fileUrl,
    // ✅ NEW: Map database status ke documentStatus
    documentStatus: doc.status,
  };
}

/**
 * Format tanggal dari ISO string ke format Indonesia
 */
function formatDate(isoDate: string): string {
  return new Date(isoDate).toLocaleDateString("id-ID", {
    day: "2-digit",
    month: "long",
    year: "numeric",
  });
}

function normalizePlaceholderValue(value?: string | null): string {
  if (!value) return "";
  return value.trim().toLowerCase() === "belum diisi" ? "" : value;
}

function pickFirstNonEmptyString(...values: unknown[]): string {
  for (const value of values) {
    if (typeof value === "string") {
      const trimmed = value.trim();
      if (trimmed.length > 0) {
        return trimmed;
      }
    }
  }
  return "";
}

function isLikelyIdentifier(value: string): boolean {
  return /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(
    value,
  );
}

function toRecord(value: unknown): Record<string, unknown> | null {
  return value && typeof value === "object"
    ? (value as Record<string, unknown>)
    : null;
}

function getPersonIdentity(value: unknown) {
  const person = toRecord(value);
  return {
    name: pickFirstNonEmptyString(
      person?.name,
      person?.nama,
      person?.fullName,
      person?.full_name,
    ),
    nim: pickFirstNonEmptyString(
      person?.nim,
      person?.studentNim,
      person?.student_nim,
    ),
    prodi: pickFirstNonEmptyString(
      person?.prodi,
      person?.programStudi,
      person?.program_studi,
    ),
    email: pickFirstNonEmptyString(person?.email),
  };
}

function extractIdentityFromOriginalName(originalName?: string | null) {
  const value = pickFirstNonEmptyString(originalName);
  if (!value) return { name: "", nim: "" };

  const namePart = value
    .replace(/\.[^.]+$/, "")
    .split("_")[0]
    .replace(/[-]+/g, " ")
    .trim();

  const nimMatch = value.match(/(?:_|-)(\d{3,})(?:\.[^.]+)?$/);

  return {
    name: namePart,
    nim: nimMatch?.[1] || "",
  };
}

/**
 * Interface untuk Team Member dari backend
 */
interface TeamMemberFromBackend {
  user?: {
    id: string;
    name: string | null;
    nim?: string | null;
    email?: string;
    prodi?: string | null;
  };
  mahasiswa?: {
    id?: string;
    name?: string | null;
    nama?: string | null;
    fullName?: string | null;
    full_name?: string | null;
    nim?: string | null;
    studentNim?: string | null;
    student_nim?: string | null;
    email?: string | null;
    prodi?: string | null;
  };
  id?: string;
  userId?: string;
  name?: string;
  nama?: string;
  fullName?: string;
  full_name?: string;
  nim?: string;
  studentNim?: string;
  student_nim?: string;
  prodi?: string;
  role: "KETUA" | "ANGGOTA";
  status?: string;
}

/**
 * Interface untuk Team dari backend
 */
type TeamFromBackend = Omit<NonNullable<Submission["team"]>, "members"> & {
  members?: TeamMemberFromBackend[];
  academicSupervisor?: string | null;
  dosenKpName?: string | null;
  dosen_kp_name?: string | null;
  dosen_name?: string | null;
  mahasiswa?: unknown;
};

/**
 * Interface untuk Submission dengan relasi Team dari backend
 */
export interface SubmissionWithTeam
  extends Omit<Submission, "team" | "wakilDekanSignature"> {
  team?: TeamFromBackend;
  wakilDekanSignature?: WakilDekanSignature | null;
}
function resolveAcademicSupervisorName(submission: SubmissionWithTeam): string {
  const team = submission.team;
  if (!team) return "-";

  const candidate = pickFirstNonEmptyString(
    team.dosenKpName,
    team.dosen_kp_name,
    team.dosen_name,
    team.academicSupervisor,
  );

  if (candidate && !isLikelyIdentifier(candidate)) {
    return candidate;
  }

  return "-";
}

function resolveMemberIdentity(
  member: TeamMemberFromBackend,
  documents: SubmissionDocument[],
) {
  const userIdentity = getPersonIdentity(member.user);
  const mahasiswaIdentity = getPersonIdentity(member.mahasiswa);
  const flatIdentity = getPersonIdentity(member);

  const uploadedDoc = documents.find(
    (doc) => doc.uploadedByMahasiswaId === member.user?.id,
  );
  const docIdentity = extractIdentityFromOriginalName(
    uploadedDoc?.originalName,
  );

  const name = pickFirstNonEmptyString(
    userIdentity.name,
    mahasiswaIdentity.name,
    flatIdentity.name,
    docIdentity.name,
  );
  const nim = pickFirstNonEmptyString(
    userIdentity.nim,
    mahasiswaIdentity.nim,
    flatIdentity.nim,
    docIdentity.nim,
  );
  const prodi = pickFirstNonEmptyString(
    userIdentity.prodi,
    mahasiswaIdentity.prodi,
    flatIdentity.prodi,
  );

  return {
    name: name || "Mahasiswa",
    nim: nim || "-",
    prodi: prodi || "-",
  };
}

/**
 * Map submission dari backend ke Application untuk admin page
 *
 * @param submission - Submission object dari backend (harus include team & documents)
 * @returns Application object untuk ditampilkan di admin page
 */
export function mapSubmissionToApplication(
  submission: SubmissionWithTeam,
): Application | null {
  // Filter hanya accepted members, dengan fallback untuk members tanpa status
  const acceptedMembers = (submission.team?.members || []).filter((m) => {
    // Jika status tidak ada, anggap sebagai ACCEPTED (fallback)
    return !m.status || m.status === "ACCEPTED";
  });
  const fallbackMembers: Member[] = [];
  if (acceptedMembers.length === 0) {
    const uploadedDocs = submission.documents || [];
    const firstDocIdentity = extractIdentityFromOriginalName(
      uploadedDocs[0]?.originalName,
    );
    fallbackMembers.push({
      id: `fallback-${submission.id}`,
      name: firstDocIdentity.name || "Mahasiswa",
      nim: firstDocIdentity.nim || "-",
      role: "Ketua",
    });
  }

  // Map members ke format yang dibutuhkan
  // Handle 2 struktur: nested user object OR flat user data
  const members: Member[] =
    acceptedMembers.length > 0
      ? acceptedMembers.map((m) => {
          const identity = resolveMemberIdentity(m, submission.documents || []);
          if (m.user) {
            return {
              id: m.user.id,
              name: identity.name,
              nim: identity.nim,
              prodi: identity.prodi !== "-" ? identity.prodi : undefined,
              role: m.role === "KETUA" ? "Ketua" : "Anggota",
            };
          }
          return {
            id: m.userId || m.id || "",
            name: identity.name,
            nim: identity.nim,
            prodi: identity.prodi !== "-" ? identity.prodi : undefined,
            role: m.role === "KETUA" ? "Ketua" : "Anggota",
          };
        })
      : fallbackMembers;

  // Sort: Ketua first
  members.sort((a, b) => {
    if (a.role === "Ketua") return -1;
    if (b.role === "Ketua") return 1;
    return 0;
  });

  // Map documents
  const documents: DocumentFile[] = (submission.documents || [])
    // ✅ CRITICAL: Exclude SURAT_PENGANTAR from mapper
    // SURAT_PENGANTAR is auto-generated and should not appear in review modal
    .filter((doc) => !isSuratPengantarDocument(doc.documentType))
    .map((doc) => {
      const uploaderId = doc.uploadedByMahasiswaId;
      const uploaderFromMembers = members.find((m) => m.id === uploaderId);
      const uploaderName =
        doc.uploadedByUser?.name ||
        uploaderFromMembers?.name ||
        extractIdentityFromOriginalName(doc.originalName).name ||
        "Mahasiswa";

      return mapSubmissionDocumentToDocumentFile(doc, uploaderName);
    })
    .filter((doc) => doc.title && doc.title !== "undefined");

  // Map status based on workflow stage (status final-only is controlled by dosen/wakil dekan)
  const rawWorkflowStage = submission.workflowStage?.toUpperCase();
  const workflowStage: Application["workflowStage"] =
    rawWorkflowStage === "PENDING_DOSEN_VERIFICATION" ||
    rawWorkflowStage === "COMPLETED" ||
    rawWorkflowStage === "REJECTED_ADMIN" ||
    rawWorkflowStage === "REJECTED_DOSEN" ||
    rawWorkflowStage === "DRAFT"
      ? rawWorkflowStage
      : "PENDING_ADMIN_REVIEW";

  let status: "pending" | "approved" | "rejected" = "pending";

  if (workflowStage === "COMPLETED") {
    status = "approved";
  } else if (
    workflowStage === "REJECTED_ADMIN" ||
    workflowStage === "REJECTED_DOSEN"
  ) {
    status = "rejected";
  }

  const pendingLabel: "Menunggu Review" | "Menunggu TTD Wakil Dekan" =
    workflowStage === "PENDING_DOSEN_VERIFICATION"
      ? "Menunggu TTD Wakil Dekan"
      : "Menunggu Review";

  const supervisor = resolveAcademicSupervisorName(submission);
  const wakilDekanSignature = submission.wakilDekanSignature || undefined;
  const letterNumber = submission.letterNumber || undefined;
  const signedFileUrl = submission.finalSignedFileUrl || undefined;

  return {
    id: parseInt(submission.id, 10) || Math.floor(Math.random() * 10000),
    submissionId: submission.id, // ✅ CRITICAL: Store original ID from database
    date: submission.submittedAt
      ? new Date(submission.submittedAt).toLocaleDateString("id-ID", {
          day: "2-digit",
          month: "2-digit",
          year: "numeric",
        })
      : new Date(submission.createdAt).toLocaleDateString("id-ID", {
          day: "2-digit",
          month: "2-digit",
          year: "numeric",
        }),
    status,
    workflowStage,
    pendingLabel,
    supervisor,
    members,
    internship: {
      tujuanSurat: normalizePlaceholderValue(submission.letterPurpose),
      namaTempat: normalizePlaceholderValue(submission.companyName),
      alamatTempat: normalizePlaceholderValue(submission.companyAddress),
      teleponPerusahaan: normalizePlaceholderValue(submission.companyPhone),
      jenisProdukUsaha: normalizePlaceholderValue(
        submission.companyBusinessType,
      ),
      divisi: normalizePlaceholderValue(submission.division),
      tanggalMulai: formatDate(submission.startDate),
      tanggalSelesai: formatDate(submission.endDate),
    },
    documents,
    wakilDekanSignature,
    letterNumber,
    signedFileUrl,
    rejectionComment:
      submission.adminRejectionReason || submission.rejectionReason,
    statusHistory: submission.statusHistory,
    documentReviews: submission.documentReviews,
  };
}

/**
 * Map array submissions ke applications
 */
export function mapSubmissionsToApplications(
  submissions: SubmissionWithTeam[],
): Application[] {
  return submissions
    .map(mapSubmissionToApplication)
    .filter((app): app is Application => app !== null);
}
